### PR TITLE
bq client supports different regions

### PR DESCRIPTION
**Pull request by thinhha**
Fixes a bug with BQ Client validation using the current project id to validate datasets in different regions.

### CODE REVIEW

**Comment by pbalm** [comment]
I kind of hate to be that guy, but this change seems a little involved (more than a few lines, and across a good number of different functions) -- would it be possible to create a test for this?

**Comment by thinhha** [comment]
Hi @pbalm, I added a few new tests in `test_bigquery_client` they are passing now.

The metadata tests are still failing however it's unrelated to this change so I'm inclined to ignore them.

Could you please take a look and approve if you can?

**Review by pbalm — APPROVED** [review]
Nice! LGTM

**Comment by thinhha** [comment]
awesome thanks!

**Pull request merged**
