### PR TITLE
Fixing an issue with conflicting names: column_id=data with the CTE data alias

### PR DESCRIPTION
**Pull request by hejnal**
This issue is specifically related to CUSTOM_SQL_EXPR which gets the column name (with no alias) and then uses it in the sql expression, e.g. REGEX check will only accepts the param of pattern. The substitution of column_id is done by the framework. In other cases, like CUSTOM_SQL_STATEMENT, the 'data' alias can be added to the sql, so there's no code change needed.

### CODE REVIEW

**Comment by pbalm** [comment]
Builds failed due to "Quota exceeded for quota metric 'Read requests for Dataplex Metadata". I hit "rerun", let's see if they pass now.

**Comment by pbalm** [comment]
Now it has a test failure, one of those that compares to the expected JSON output I think: `test_prepare_configs_from_rule_binding`

**Review by pbalm — APPROVED** [review]
LGTM

**Comment by thinhha** [comment]
Merging despite test failures because the metadata read quota issues have nothing to do with this change. The Cloud Build tests are more comprehensive than the github action tests so I think we're good to merge.

**Comment by hejnal** [comment]
great, thanks folks!

**Pull request merged**
